# Generated by Django 5.1.1 on 2024-10-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='loyaltyPoints',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
