# Generated by Django 5.0.6 on 2024-11-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
    ]
