# Generated by Django 5.1.1 on 2024-10-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(blank=True, default='Silver User', max_length=50),
        ),
    ]
